version: '3.9'

services:
  mailing-service:
    build: .
    container_name: mailingServiceContainer
    ports:
      - "8002:8000"
    networks:
      - stockTrackerDockerNetwork

networks:
  stockTrackerDockerNetwork:
    external: true