version: '3.9'

services:
  db_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: sysad.stock.tracker@gmail.com
      SMTP_PASSWORD: goczmulgrxsbfesa