version: '3.9'

services:
  db_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587 # oder 25 oder 465
      SMTP_USER: sysad.project.ws2425@gmail.com
      SMTP_PASSWORD: SysAdProjectWs2425