@startuml

actor "DatabaseService" as Database
participant "Api" as API
participant "ApiBF" as ApiBF
participant "MailPreparingServiceBa" as MailPreparingService
participant "MailSendingServiceBa" as MailSendingService
participant "Gmail" as Gmail

Database -> API: POST /send_update_mail
API -> ApiBF: Validated update mail request
ApiBF -> MailPreparingService: Unpacked mailing data
MailPreparingService -> MailPreparingService: Prepare and save update mail data
MailPreparingService -> MailSendingService: Update mailing data all 2 seconds
MailSendingService -> Gmail: Send update mail
Gmail --> MailSendingService: Update mail sent confirmation
MailSendingService --> MailPreparingService: Successfully sent update mail
MailPreparingService --> ApiBF: Successfully sent update mail
ApiBF --> API: Successfully sent update mail response
API --> Database: JSONResponse (update mail sent)

Database -> API: POST /send_error_mail
API -> ApiBF: Validated error mail request
ApiBF -> MailPreparingService: Unpacked error mail data
MailPreparingService -> MailPreparingService: Prepare error mail
MailPreparingService -> MailSendingService: Prepared error mail
MailSendingService -> Gmail: Send error mail
Gmail --> MailSendingService: Error mail sent confirmation
MailSendingService --> MailPreparingService: Successfully sent error mail
MailPreparingService --> ApiBF: Successfully sent error mail
ApiBF --> API: Successfully sent error mail response
API --> Database: JSONResponse (error mail sent)

@enduml