

services:
  stock-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_tracker_container
    ports:
      - "8080:80"
    environment:
      - DATABASE_SERVICE_URL="http://localhost:8001/updateApp"
    networks:
      - stockTrackerDockerNetwork

networks:
  stockTrackerDockerNetwork:
    external: true

