

services:
  stock-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_tracker_container
    ports:
      - "8081:8081"
    environment:
      - DATABASE_SERVICE_URL="http://localhost:8001/update_app"
    networks:
      - stockTrackerDockerNetwork

networks:
  stockTrackerDockerNetwork:
    external: true

