services:
  detection-service:
    extends: .common_nvidia

  .common:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_SERVICE_URL= http://dataBaseServiceContainer:8000
      - MQTT_BROKER_URL=stocktracker-mosquitto
      - MQTT_BROKER_PORT=1883
      - HUMAN_CHECK_MODEL=./app/models/humancheck/yolo11n.pt
      - DETECTION_MODEL=./app/models/detection/yolo11n.pt
      - DEVICE_TO_RUN_MODEL=cuda # cuda or cpu#
      - SERVER_IP=192.168.1.191

  .common_nvidia:
    extends: .common
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES= all
      - NVIDIA_DRIVER_CAPABILITIES= compute,video,utility,graphics
