version: "3.9"
services:
  detection-service:
    build: .
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DATABASE_SERVICE_URL="http://database-service-url"
      - CAM_SERVICE_URL="http://127.0.0.1:7999/video"