version: "3.9"
services:
  detection-service:
    build: .
    ports:
      - "8000:8000"
    devices:
      - "/dev/video2:/dev/video0"
    environment:
      - DATABASE_SERVICE_URL=http://192.168.2.15:8181