version: '3.9'
services:
  detectionservice:
  build:
    context: .
  environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"  
  networks:
    - stockTrackerDockerNetwork
  depends_on:
    - db-service