@startuml

node detection {
    component camera
    component detectionService {
        portout addItemsOUT
        portout deleteItemsOUT
        portout feedIN
        portout trackIN
    }
}
node database {
    database postgresDatabase
    component databaseService{
        portin addItemsIN
        portin deleteItemsIN

        portin getDataIN

        portout send_update_mail_OUT
        portout send_error_mail_OUT
    }
}
node mail {
    component mailService{
        portin send_update_mail_IN
        portin send_error_mail_IN
    }
}
node appWebsite {
    component flutterApp {
        portout getDataOUT
        portin feedOUT
        portin trackOUT
    }
}

camera -down-> detectionService

addItemsOUT -down-> addItemsIN
deleteItemsOUT -down-> deleteItemsIN

getDataOUT -down-> getDataIN

feedOUT -right-> feedIN
trackOUT -right-> trackIN

send_update_mail_OUT -down-> send_update_mail_IN
send_error_mail_OUT -down-> send_error_mail_IN

databaseService -left-> postgresDatabase

@enduml