@startuml
entity "Camera" as Camera
participant "Camera-Service" as CameraService
participant "MQTT-Brocker" as MQTTBrocker
participant "Detection-Service" as DetectionService
participant "Database-Service" as DatabaseService
database "Database" as Database
participant "Flutter-App" as FlutterApp
participant "Mailing-Service" as MailingService

Camera -> CameraService: Frames
CameraService -> MQTTBrocker: Frames
MQTTBrocker -> DetectionService: Frames
DetectionService -> DatabaseService: Send product updates all 15 seconds
DetectionService -> DatabaseService: Or send product updates if detected
DatabaseService -> Database: Saves and updates products data
DatabaseService -> MailingService: Forwards updates to MailingService
FlutterApp -> DatabaseService: Requests updates all 10 seconds
@enduml