version: "3.9"
services:
  cam-service:
    build: .
    devices:
      - "/dev/video2:/dev/video0"
    environment:
      - MQTT_BROKER_URL=192.168.2.15
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=sysAdmin
      - MQTT_PASSWORD=sysAd2024
