openapi: 3.0.3

info:
  title: Database-Service API
  description: This is the API-Specification for the Database-Service
  version: 1.0.0

paths:
  /update_products:
    post:
      summary: Initialise products or update product amount
      description: When used for initialising, then products-types are added to the database. Used to update products amoutn, pictures and overall-picture.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '2XX':
          description: Succesfully updated item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '4XX':
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /update_app:
    get:
      summary: Sends products update to app
      description: The app can use this to get updates on products regarding amount, picture and overall-picture.
      responses:
        '2XX':
          description: Succesfully sent update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppResponse'
        '4XX':
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppResponse'
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppResponse'
    
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        amount:
          type: integer
        picture:
          type: string
          nullable: true
      required:
        - name
        - amount

    Request:
      type: object
      properties:
        products:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Product'
        overall_picture:
          type: string
      required:
       - products
       - overall_picture

    Response:
      type: object 
      properties:
        status_code:
          type: integer
      required:
       - status_code

    AppResponse:
      type: object
      properties:
        products:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Product'
        overall_picture:
          type: string
      required:
       - products