version: '3.8'

services:
  database-service:
    build:
      context: .
    container_name: dataBaseServiceContainer
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db   # Dummy-Datenbank-URL für Entwicklung
    networks:
      - stockTrackerDockerNetwork


networks:
  stockTrackerDockerNetwork:
    external: true