version: '3.8'

services:
  db_service:
    build: 
      context: .

    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

    networks:
      - stockTrackerDockerNetwork
    ports:
      - "8000:8000"
    depends_on:
      - db