version: '3.8'

services:
  database-service:
    build:
      context: .
    container_name: dataBaseServiceContainer
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@stock_tracker_postgres_db:5432/mydatabase   # Dummy-Datenbank-URL für Entwicklung
      - MAILING_SERVICE_URL=http://mailing-service:8002/
    networks:
      - stockTrackerDockerNetwork

networks:
  stockTrackerDockerNetwork:
    external: true