openapi: 3.0.3

info:
  title: Mailing-Service API
  description: This is the API-Specification for the Mailing-Service
  version: 1.0.0

paths:
  /send_mail_added:
    post:
      summary: Interface for sending an email that a product was added
      description: Interface for sending an email with the given data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mail_data_array'
      responses:
        '2XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
        '4XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
        '5XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
  /send_mail_deleted:
    post:
      summary: Interface for sending an email that a product was deleted
      description: Interface for sending an email with the given data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mail_data_array'
      responses:
        '2XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
        '4XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
        '5XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
  /send_error_mail:
    post:
      summary: Interface for sending an email that an error occurred
      description: Interface for sending an email with the given data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/error_mail_data'
      responses:
        '2XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
        '4XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'
        '5XX':
          description: Response of the mailing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json_response'

components:
  schemas:
    mail_data:
      type: object
      required:
        - product_id
        - product_name
        - product_amount_changed
        - product_amount_total
      properties:
        product_id:
          type: integer
          example: 1
        product_name:
          type: string
          example: "Müsli"
        product_amount_changed:
          type: integer
          example: 2
        product_amount_total:
          type: integer
          example: 5
    mail_data_array:
      type: array
      items:
        $ref: '#/components/schemas/mail_data'
      description: An array of MailData objects
      example:
        - product_id: 1
          product_name: "Müsli"
          product_amount_changed: 2
          product_amount_total: 5
        - product_id: 2
          product_name: "Wasser"
          product_amount_changed: 2
          product_amount_total: 5
    error_mail_data:
      type: object
      required:
        - error_message
      properties:
        error_message:
          type: string
          example: "The database service couldn't save the product"
    json_response:
      type: object
      properties:
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: "Message sent successfully"
