@startuml

class API {
    ApiBF apiBf
    ApiRouter router
    Validator validator

    String sendMailAdded(Request request)
    JSONResponse sendMailDeleted(Request request)
    JSONResponse sendErrorMail(Request request)
}

class Validator {
    void __init__(self)
    JSONResponse prepareMailingData(self, Request validData, Action action)
    JSONResponse sendMail
}

@enduml
