version: '3.9'

services:
  db:
    build: .
    container_name: stock_tracker_postgres_db_main
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

volumes:
  pgdata: