@startuml

node detection {
    component camera
    component detectionService {
        portout addItemOUT
        portout deleteItemOUT
        portout getNextIdOUT
        portout feedIN
        portout trackIN
    }
}
node database {
    database postgresDatabase
    component databaseService{
        portin addItemIN
        portin deleteItemIN
        portin getNextIdIN

        portin getDataIN

        portout sendMailAddedOUT
        portout sendMailDeletedOUT
        portout sendErrorMailOUT
    }
}
node mail {
    component mailService{
        portin sendMailAddedIN
        portin sendMailDeletedIN
        portin sendErrorMailIN
    }
}
node appWebsite {
    component flutterApp {
        portout getDataOUT
        portin feedOUT
        portin trackOUT
    }
}

camera -down-> detectionService

addItemOUT -down-> addItemIN
deleteItemOUT -down-> deleteItemIN
getNextIdOUT -down-> getNextIdIN

getDataOUT -down-> getDataIN

feedOUT -right-> feedIN
trackOUT -right-> trackIN

sendMailAddedOUT -down-> sendMailAddedIN 
sendMailDeletedOUT -down-> sendMailDeletedIN
sendErrorMailOUT -down-> sendErrorMailIN

databaseService -left-> postgresDatabase

@enduml