@startuml

node detection {
    component camera
    component detectionService {
        portout addItemsOUT
        portout deleteItemsOUT
        portout feedIN
        portout trackIN
    }
}
node database {
    database postgresDatabase
    component databaseService{
        portin addItemsIN
        portin deleteItemsIN

        portin getDataIN

        portout sendUpdateMailOUT
        portout sendErrorMailOUT
    }
}
node mail {
    component mailService{
        portin sendUpdateMailIN
        portin sendErrorMailIN
    }
}
node appWebsite {
    component flutterApp {
        portout getDataOUT
        portin feedOUT
        portin trackOUT
    }
}

camera -down-> detectionService

addItemsOUT -down-> addItemsIN
deleteItemsOUT -down-> deleteItemsIN

getDataOUT -down-> getDataIN

feedOUT -right-> feedIN
trackOUT -right-> trackIN

sendUpdateMailOUT -down-> sendUpdateMailIN
sendErrorMailOUT -down-> sendErrorMailIN

databaseService -left-> postgresDatabase

@enduml