version: "3.9"
services:
  detection-service:
    container_name: detectionServiceContainer
    build: ./detectionService
    networks:
      - stockTrackerDockerNetwork
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DATABASE_URL="http://database-url"

  mailing-service:
    build: ./mailingService
    container_name: mailingServiceContainer
    networks:
      - stockTrackerDockerNetwork
    ports:
      - "8002:8000"
    environment:
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: sysad.stock.tracker@gmail.com
      SMTP_PASSWORD: qlddayafyvqszzlt


networks:
  stockTrackerDockerNetwork:
    driver: bridge

