version: "3.9"
services:
  stock_tracker_postgres_db:
    build: ./database
    container_name: databaseContainer
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - stockTrackerDockerNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  database-service:
    build: ./databaseService
    container_name: dataBaseServiceContainer
    networks:
      - stockTrackerDockerNetwork
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@databaseContainer:5432/mydatabase
      - MAILING_SERVICE_URL=http://mailing-service:8000/
    depends_on:
      stock_tracker_postgres_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/updateApp || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  detection-service:
    container_name: detectionServiceContainer
    build: ./detectionService
    networks:
      - stockTrackerDockerNetwork
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DATABASE_SERVICE_URL=http://dataBaseServiceContainer:8000
    depends_on:
      database-service:
        condition: service_healthy

  mailing-service:
    build: ./mailingService
    container_name: mailingServiceContainer
    networks:
      - stockTrackerDockerNetwork
    ports:
      - "8002:8000"
    environment:
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: sysad.stock.tracker@gmail.com
      SMTP_PASSWORD: qlddayafyvqszzlt

  
  

volumes:
  pgdata:

networks:
  stockTrackerDockerNetwork:
    driver: bridge
